# base image
FROM python:3.7.2-slim

# install dependencies
RUN apt-get update && \
    apt-get install -y build-essential gcc python3-dev musl-dev && \
    apt-get install -y postgresql-server-dev-all && \
    apt-get install -y netcat-openbsd

# set working directory
WORKDIR /usr/src/app

RUN pip install --upgrade pip

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint-prod.sh
RUN chmod +x /usr/src/app/entrypoint-prod.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/entrypoint-prod.sh"]
